Truncate title names to fix very long name issue
cboddy/i3-workspace-names-daemon pull request #17
Opened 2019-10-26 07:30 UTC by cedl38

2019-11-04 17:02 UTC, cboddy requested changes

2019-11-04 17:02 UTC, cboddy commented on i3_workspace_names_daemon.py
> +def build_rename(i3, app_icons, delim, lenght, uniq):
mind fixing the typo?

2019-11-04 17:02 UTC, cboddy commented on i3_workspace_names_daemon.py
> +def build_rename(i3, app_icons, delim, lenght, uniq):
and in the other two places, please.

2019-11-04 17:03 UTC, cboddy commented
One minor comment, otherwise LGTM!

2019-11-17 14:04 UTC, merged

2019-11-17 14:24 UTC, cboddy commented
@cedl38  thanks for this. I've fixed the typos and a bug that caused the icon lookup to fail - see [5d37153f](chttps://github.com/cboddy/i3-workspace-names-daemon/commit/5d37153fcc4bde5c8b800be1dd6cb90d9426d8c8).

This is now pushed to pypi in version ``0.13.0``.

2019-11-17 20:23 UTC, cedl38 commented
> @cedl38 thanks for this. I've fixed the typos and a bug that caused the icon lookup to fail - see [5d37153](https://github.com/cboddy/i3-workspace-names-daemon/commit/5d37153fcc4bde5c8b800be1dd6cb90d9426d8c8).
> 
> This is now pushed to pypi in version `0.13.0`.

Sorry I forget to make requested changes. Thanks for fixing it :)